variables:
  GET_SOURCES_ATTEMPTS: 3


mybuild:
    image: python:3.5-slim
    before_script:
    - pip3 install pytest-cov
    script:
    - pytest --cov=numerical numericaltest.py
    tags:
    - docker
